<?php
$team_names = [
0 => 'Paris',
1 => 'Marseille',
2 => 'Lyon',
3 => 'Toulouse',
4 => 'Nice',
5 => 'Nantes',
6 => 'Strasbourg',
7 => 'Montpellier',
8 => 'Bordeaux',
9 => 'Lille',
10 => 'Rennes',
11 => 'Reims',
12 => 'Le Havre',
13 => 'Saint-Étienne',
14 => 'Toulon',
15 => 'Grenoble',
16 => 'Dijon',
17 => 'Angers',
18 => 'Nîmes',
19 => 'Villeurbanne',
];
